site_name: KnowTouch 2016 Dokumentation
site_url: https://cogneon.github.io/knt16doku/de/
docs_dir: src
site_dir: ../docs/de
edit_uri: ''

nav:
    - Willkommen: index.md
    - Vorab-Webinare:
      - Angelika Mittelmann: 1-1-mittelmann.md
      - Peter Sch체tt: 1-2-schuett.md
      - Werner Sauter, Jochen Robes, Daniel Stoller-Schai: 1-3-sauter-robes-stoller-schai.md
      - Nick Milton: 1-4-milton.md
    - Keynotes:
      - Simon D체ckert: 2-1-dueckert.md
      - Stefan K체hl: 2-2-kuehl.md
      - Peter Pawlowsky: 2-3-pawlowsky.md
      - Kai Romhardt: 2-4-romhardt.md
    - Vortr채ge:
      - Karsten Ehms: 3-1-ehms.md
      - Ulrich Schmidt: 3-2-schmidt.md
      - Eva-Maria Bruch, Martin Kimmich: 3-3-bruch-kimmich.md
      - Werner Stockinger: 3-4-stockinger.md
      - Thomas Jenewein: 3-5-jenewein.md
      - Anna Gutzmann, Gudrun Behm-Steidel: 3-6-gutzmann-behm-steidel.md
      - Paul Seren: 3-7-seren.md
      - Franz Lehner: 3-8-lehner.md
    - Sessions: 4-0-sessions.md
    - Anhang: 5-0-appendix.md
    - Download:
      - PDF-Version: https://github.com/cogneon/knt16doku/blob/master/de/knt16-Documentation-de.pdf
      - Word-Version: https://github.com/cogneon/knt16doku/blob/master/de/knt16-Documentation-de.docx
      - HTML-Version: https://github.com/cogneon/knt16doku/blob/master/de/knt16-Documentation-de.html
      - E-Book-Version: https://github.com/cogneon/knt16doku/blob/master/de/knt16-Documentation-de.epub
      - Markdown: https://github.com/cogneon/knt16doku/blob/master/de/knt16-Documentation-de.md


theme:
    name: 'material'
#    custom_dir: src/overrides
    palette:
        primary: black
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github
    features:
      - search.share

#extra_css:
#  - stylesheets/extra.css

repo_name: 'cogneon/loscon25doku'
repo_url: 'https://github.com/cogneon/loscon25doku'

extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/groups/8682361/'
    generator: false

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
plugins:
  - search